In [1]:
def himmelblau(x):
    return (x[0] **2 + x[1] - 11) ** 2 + (x[0] + x[1]**2 -7) **2

In [2]:
import numpy as np 

x = np.arange(-6, 6, 0.1)
y = np.arange(-6, 6, 0.1)

X,Y = np.meshgrid(x,y)

X,Y

(array([[-6. , -5.9, -5.8, ...,  5.7,  5.8,  5.9],
        [-6. , -5.9, -5.8, ...,  5.7,  5.8,  5.9],
        [-6. , -5.9, -5.8, ...,  5.7,  5.8,  5.9],
        ...,
        [-6. , -5.9, -5.8, ...,  5.7,  5.8,  5.9],
        [-6. , -5.9, -5.8, ...,  5.7,  5.8,  5.9],
        [-6. , -5.9, -5.8, ...,  5.7,  5.8,  5.9]]),
 array([[-6. , -6. , -6. , ..., -6. , -6. , -6. ],
        [-5.9, -5.9, -5.9, ..., -5.9, -5.9, -5.9],
        [-5.8, -5.8, -5.8, ..., -5.8, -5.8, -5.8],
        ...,
        [ 5.7,  5.7,  5.7, ...,  5.7,  5.7,  5.7],
        [ 5.8,  5.8,  5.8, ...,  5.8,  5.8,  5.8],
        [ 5.9,  5.9,  5.9, ...,  5.9,  5.9,  5.9]]))

In [3]:
Z = himmelblau((X,Y))
Z

array([[ 890.    ,  850.8061,  815.1296, ..., 1444.0301, 1487.9296,
        1535.2061],
       [ 840.4861,  800.8162,  764.6677, ..., 1365.9682, 1409.8597,
        1457.1322],
       [ 794.6496,  754.5077,  717.8912, ..., 1292.0517, 1335.9392,
        1383.2117],
       ...,
       [1322.3501, 1254.6082, 1190.8517, ..., 1712.1122, 1782.2197,
        1856.1722],
       [1374.6496, 1306.8997, 1243.1392, ..., 1790.6197, 1861.1872,
        1935.6037],
       [1430.4861, 1362.7322, 1298.9717, ..., 1873.1322, 1944.1637,
        2019.0482]])

In [4]:
import sys
sys.path = ['C:\\Users\\74098\\anaconda3\\envs\\pytorch\\Scripts',
 'C:\\Users\\74098\\anaconda3\\envs\\pytorch\\python38.zip',
 'C:\\Users\\74098\\anaconda3\\envs\\pytorch\\DLLs',
 'C:\\Users\\74098\\anaconda3\\envs\\pytorch\\lib',
 'C:\\Users\\74098\\anaconda3\\envs\\pytorch',
 '',
 'C:\\Users\\74098\\AppData\\Roaming\\Python\\Python38\\site-packages',
 'C:\\Users\\74098\\anaconda3\\envs\\pytorch\\lib\\site-packages',
 'C:\\Users\\74098\\anaconda3\\envs\\pytorch\\lib\\site-packages\\win32',
 'C:\\Users\\74098\\anaconda3\\envs\\pytorch\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\74098\\anaconda3\\envs\\pytorch\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\74098\\AppData\\Roaming\\Python\\Python38\\site-packages\\IPython\\extensions',
 'C:\\Users\\74098\\.ipython']
import matplotlib.pyplot as plt 

fig = plt.figure()
ax = plt.gca(projection='3d')
ax.plot_surface(X,Y,Z)
plt.show()


ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

In [5]:
import torch
x = torch.tensor([0., 0.], requires_grad=True)
optimizer = torch.optim.Adam([x], lr=1e-3)


In [6]:
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
for step in range(20000):

    pred = himmelblau(x)

    optimizer.zero_grad()
    pred.backward()
    optimizer.step()

    if step % 2000 ==0:
        print('step {}: x={}. f(x)={}'.format(step, x.cpu().tolist(), pred.item()))

step 0: x=[0.0009999999310821295, 0.0009999999310821295]. f(x)=170.0
step 2000: x=[2.3331806659698486, 1.9540694952011108]. f(x)=13.730916023254395
step 4000: x=[2.9820079803466797, 2.0270984172821045]. f(x)=0.014858869835734367
step 6000: x=[2.999983549118042, 2.0000221729278564]. f(x)=1.1074007488787174e-08
step 8000: x=[2.9999938011169434, 2.0000083446502686]. f(x)=1.5572823031106964e-09
step 10000: x=[2.999997854232788, 2.000002861022949]. f(x)=1.8189894035458565e-10
step 12000: x=[2.9999992847442627, 2.0000009536743164]. f(x)=1.6370904631912708e-11
step 14000: x=[2.999999761581421, 2.000000238418579]. f(x)=1.8189894035458565e-12
step 16000: x=[3.0, 2.0]. f(x)=0.0
step 18000: x=[3.0, 2.0]. f(x)=0.0
