In [1]:
import torch

a = torch.FloatTensor([1,2,3])
b = torch.FloatTensor([1])

a+b

tensor([2., 3., 4.])

In [2]:
a = torch.FloatTensor([1,2,3])
b = torch.FloatTensor([
    [1,1,1],[1,1,1],[1,1,1]
])

a+b

tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])

In [5]:
a = torch.FloatTensor([1,2,3]).reshape(3,1)
b = torch.FloatTensor([
    [1,1,1],[1,1,1],[1,1,1]
])

a+b

tensor([[2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [6]:
a = torch.FloatTensor([4,32,14,14])
b = torch.FloatTensor([1,2])

a+b

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0

In [7]:
import torch

a = torch.FloatTensor([1,2,3])
b = torch.FloatTensor([[1]])

a+b

tensor([[2., 3., 4.]])