# Math Operation

## add sub mul div

In [2]:
import  torch

a = torch.rand(3,4)
b = torch.rand(4)

a+b

tensor([[1.0918, 0.2090, 0.0784, 0.1730],
        [0.7621, 0.2056, 0.0869, 0.2177],
        [1.0134, 0.7675, 0.5322, 0.0675]])

In [3]:
torch.add(a,b)

tensor([[1.0918, 0.2090, 0.0784, 0.1730],
        [0.7621, 0.2056, 0.0869, 0.2177],
        [1.0134, 0.7675, 0.5322, 0.0675]])

In [4]:
a.add(b)

tensor([[1.0918, 0.2090, 0.0784, 0.1730],
        [0.7621, 0.2056, 0.0869, 0.2177],
        [1.0134, 0.7675, 0.5322, 0.0675]])

In [5]:
torch.all(torch.eq(a+b, torch.add(a,b)))

tensor(True)

##  matrix multiply

In [6]:
a.matmul(b)

tensor([0.1419, 0.0998, 0.2130])

In [8]:
a = torch.rand(3,4)
b = torch.rand(4,7)

a.matmul(b).shape

torch.Size([3, 7])

In [9]:
a @ b

tensor([[1.1193, 1.0886, 1.6894, 1.5412, 1.5942, 1.3346, 1.0120],
        [0.4354, 0.5827, 1.2219, 1.3263, 1.3065, 0.9433, 0.4254],
        [0.4825, 0.3199, 0.5886, 0.8760, 1.2905, 0.7208, 0.5107]])

In [10]:
# linear layer
a = torch.rand(4, 784)

x = torch.rand(4, 784)

w = torch.rand(512, 784)

(x @ w.t()).shape

torch.Size([4, 512])

In [13]:
a = torch.rand(4,3,28,64)
b = torch.rand(4,3,64,32)


# 将后面两个dim运算
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [14]:
a = torch.rand(4,3,28,64)
b = torch.rand(4,1,64,32)


# broadcast
torch.matmul(a,b).shape

torch.Size([4, 3, 28, 32])

In [20]:
a = torch.full([2,2], 3.)
a

tensor([[3., 3.],
        [3., 3.]])

In [21]:
a ** 2

tensor([[9., 9.],
        [9., 9.]])

In [22]:
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [23]:
torch.sqrt(a**2)

tensor([[3., 3.],
        [3., 3.]])

In [25]:
(a **2) ** 0.5

tensor([[3., 3.],
        [3., 3.]])

In [30]:
a = torch.exp(torch.ones(2,2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [28]:
a.log()

tensor([[1., 1.],
        [1., 1.]])

## round ceil floor 略

## clamp

In [31]:
grad = torch.randn(2,3)*15
grad

tensor([[ 15.8116,  -3.1252,  13.2798],
        [-29.7160, -10.4573,  16.8610]])

In [33]:
grad.max()

tensor(16.8610)

In [35]:
grad.min()

tensor(-29.7160)

In [37]:
# 梯度裁剪
grad.clamp(10)

tensor([[15.8116, 10.0000, 13.2798],
        [10.0000, 10.0000, 16.8610]])

In [39]:
grad.clamp(-10,10)

tensor([[ 10.0000,  -3.1252,  10.0000],
        [-10.0000, -10.0000,  10.0000]])