# gradient

In [27]:
import torch

x = torch.ones(1)
w = torch.full([1], 2.).requires_grad_(True)

mse = torch.nn.functional.mse_loss(torch.ones([1]), x*w)
mse

tensor(1., grad_fn=<MseLossBackward>)

In [24]:
w

tensor([2.], requires_grad=True)

In [12]:
torch.autograd.grad(mse, [w])

(tensor([2.]),)

In [29]:
# 注意不要重复计算导数
x = torch.ones(1)
w = torch.full([1], 2.).requires_grad_(True)

mse = torch.nn.functional.mse_loss(torch.ones([1]), x*w)
# 反向传播 自动求导 赋值到tensor的grad上
mse.backward()
w.grad

tensor([2.])

# softmax

In [34]:
from torch.nn import functional as F 

a = torch.rand(3).requires_grad_()
a

tensor([0.5650, 0.2519, 0.9100], requires_grad=True)

In [40]:
F.softmax(a, dim=0)

tensor([0.3182, 0.2326, 0.4492], grad_fn=<SoftmaxBackward>)