# advanced op

In [1]:
import torch

In [2]:
a = torch.rand(3,3)
b = torch.rand(3,3)

torch.where(a>b, a, b)


tensor([[0.8609, 0.2816, 0.2694],
        [0.6358, 0.9908, 0.8757],
        [0.9607, 0.7550, 0.1477]])

In [3]:
a

tensor([[0.8609, 0.1536, 0.2694],
        [0.6358, 0.0524, 0.8757],
        [0.9607, 0.7550, 0.0492]])

In [4]:
b

tensor([[0.5613, 0.2816, 0.1953],
        [0.3238, 0.9908, 0.2533],
        [0.3256, 0.7089, 0.1477]])

In [7]:
torch.where(a>b, torch.tensor(1.), torch.tensor(0.))

tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 0.]])

## where 可以在gpu上运算

In [4]:
a = torch.tensor([1,2,3,4])

b = torch.tensor([2,3,2,1,1,0,2,3,0,1])
torch.gather(a, 0, index=b)

tensor([3, 4, 3, 2, 2, 1, 3, 4, 1, 2])