# perceptron

In [6]:
import torch
from torch.nn import functional as F 

In [11]:
x = torch.randn(1, 10)
x

tensor([[ 1.2489,  1.5276,  1.0413, -1.2716,  1.0283, -0.9990, -0.6769,  0.2925,
         -1.6257,  0.2720]])

In [12]:
w = torch.randn(1, 10).requires_grad_()
w

tensor([[-1.7138, -0.4883, -0.7842, -0.7603, -0.7296,  1.9137, -1.4743,  0.8976,
         -0.0138,  0.7564]], requires_grad=True)

In [15]:
o = torch.sigmoid(x.mul(w).t())
o

tensor([[0.1052],
        [0.3217],
        [0.3065],
        [0.7245],
        [0.3208],
        [0.1288],
        [0.7306],
        [0.5653],
        [0.5056],
        [0.5512]], grad_fn=<SigmoidBackward>)

In [17]:
loss = F.mse_loss(torch.ones(10,1), o)
loss

tensor(0.3745, grad_fn=<MseLossBackward>)

In [18]:
loss.backward()

In [19]:
w.grad

tensor([[-0.0210, -0.0452, -0.0307,  0.0140, -0.0304,  0.0195,  0.0072, -0.0063,
          0.0402, -0.0060]])

In [20]:
w = w - 0.001*w.grad
w

tensor([[-1.7138, -0.4882, -0.7842, -0.7604, -0.7296,  1.9136, -1.4743,  0.8976,
         -0.0138,  0.7564]], grad_fn=<SubBackward0>)

# 2dim

In [31]:
x = torch.rand(1,10)
w = torch.rand(2,10).requires_grad_()
w

tensor([[0.9207, 0.7551, 0.2838, 0.4564, 0.0722, 0.9858, 0.4710, 0.4593, 0.9837,
         0.6932],
        [0.4991, 0.5589, 0.4842, 0.0146, 0.5032, 0.5601, 0.7340, 0.3843, 0.3013,
         0.1958]], requires_grad=True)

In [32]:
o = torch.sigmoid(x.mul(w).t())
o

tensor([[0.7139, 0.6214],
        [0.6630, 0.6227],
        [0.5361, 0.5614],
        [0.5729, 0.5023],
        [0.5026, 0.5180],
        [0.7097, 0.6243],
        [0.5953, 0.6459],
        [0.5337, 0.5282],
        [0.5402, 0.5123],
        [0.5946, 0.5270]], grad_fn=<SigmoidBackward>)

In [33]:
loss = F.mse_loss(torch.ones_like(o),o)
loss

tensor(0.1795, grad_fn=<MseLossBackward>)

In [34]:
loss.backward()
w.grad

tensor([[-0.0058, -0.0067, -0.0059, -0.0067, -0.0018, -0.0054, -0.0080, -0.0034,
         -0.0019, -0.0054],
        [-0.0088, -0.0079, -0.0055, -0.0080, -0.0017, -0.0080, -0.0066, -0.0035,
         -0.0020, -0.0065]])