In [2]:
import torch

# norm_p 范数

In [6]:
a = torch.full([8], 1)
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
b = a.view(2, 4)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
c = a.view(2,2,2)
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [15]:
# 1范数是所有元素的和
a.norm(1), b.norm(1), c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [16]:
# 2范数是平方和开根号
a.norm(2), b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [17]:
# 在维度上做
b.norm(1, dim=1)

tensor([4., 4.])

In [21]:
b.norm(2, dim=1)

tensor([2., 2.])

In [22]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

# statistics


In [25]:
a = torch.arange(8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [27]:
a.min()

tensor(0.)

In [29]:
a.max()

tensor(7.)

In [30]:
a.mean()

tensor(3.5000)

In [32]:
a.sum()

tensor(28.)

In [40]:
# 展平了
a.argmax()

tensor(7)

In [44]:
# 每一个维度上的最大值weizhi
a.argmax(dim=1)

tensor([3, 3])

# dim，keepdim

In [3]:
a = torch.rand(4,10)
a.shape

torch.Size([4, 10])

In [46]:
# 返回一个元组 对应数据和索引
a.max(dim=1)

torch.return_types.max(
values=tensor([0.7878, 0.7523, 0.9034, 0.8605]),
indices=tensor([1, 7, 2, 4]))

In [47]:
# 保持原来的dim
a.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[0.7878],
        [0.7523],
        [0.9034],
        [0.8605]]),
indices=tensor([[1],
        [7],
        [2],
        [4]]))

# top-k

In [54]:
# 相比max返回更多的数据
a.topk(3, dim=1)

torch.return_types.topk(
values=tensor([[0.7878, 0.7589, 0.6268],
        [0.7523, 0.7148, 0.6667],
        [0.9034, 0.7010, 0.6807],
        [0.8605, 0.7758, 0.7228]]),
indices=tensor([[1, 2, 7],
        [7, 4, 8],
        [2, 0, 1],
        [4, 7, 0]]))

In [55]:
# 类似min
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[0.0222, 0.1582, 0.2422],
        [0.0431, 0.0973, 0.1481],
        [0.0245, 0.0611, 0.2893],
        [0.1740, 0.2421, 0.3769]]),
indices=tensor([[5, 6, 4],
        [1, 0, 2],
        [9, 3, 7],
        [5, 2, 6]]))

In [4]:
# 第2小  默认是小
a.kthvalue(2, dim=1, keepdim=True)

torch.return_types.kthvalue(
values=tensor([[0.3594],
        [0.1806],
        [0.2165],
        [0.1463]]),
indices=tensor([[5],
        [8],
        [2],
        [8]]))

# compare

In [5]:
a > 0

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [8]:
torch.gt(a, 0.5)

tensor([[False,  True,  True,  True,  True, False,  True, False, False,  True],
        [False, False,  True,  True,  True,  True,  True,  True, False, False],
        [False, False, False,  True, False, False,  True,  True,  True, False],
        [ True, False,  True,  True,  True, False,  True,  True, False,  True]])

In [10]:
torch.equal(a, a)

True