# 基本数据类型

In [2]:
import torch

# 2行3列
a = torch.randn(2, 3)
a

tensor([[-0.5934,  1.9878, -0.2270],
        [-0.5647, -0.1284,  1.6829]])

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a, torch.FloatTensor)

True

In [6]:
isinstance(a, torch.cuda.FloatTensor)

False

In [7]:
isinstance(a.cuda(), torch.cuda.FloatTensor)

True

## 标量 dim0 一般用来计算loss

In [8]:
torch.tensor(1.)

tensor(1.)

In [9]:
torch.tensor(1.3)

tensor(1.3000)

## dim 1 一般用来表示bias 或linear input （flatten）

In [11]:
torch.tensor([1.1])

tensor([1.1000])

In [12]:
torch.cuda.FloatTensor([1,2,3])

tensor([1., 2., 3.], device='cuda:0')

In [23]:
# 随机的是
torch.FloatTensor(3)

tensor([9.2196e-41, 6.1989e-06, 0.0000e+00])

In [24]:
import numpy as np 

n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [25]:
torch.from_numpy(n)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

## 判断dim

In [27]:
b = torch.ones(3)
b

tensor([1., 1., 1.])

In [30]:
b.shape

torch.Size([3])

In [31]:
b.size()

torch.Size([3])

## dim2  linear batch input

In [45]:
c = torch.randn(2,3)
c

tensor([[ 1.1936, -1.6424,  1.5530],
        [-0.3289,  1.3141, -0.7251]])

In [46]:
c.size()

torch.Size([2, 3])

In [47]:
c.size(0)

2

In [48]:
c.size(1)

3

In [50]:
list(c.shape)

[2, 3]

## dim3

In [52]:
torch.randn(1,2,3)

tensor([[[ 0.2386,  1.1075,  0.0956],
         [-0.7472, -0.2011, -0.6228]]])

## dim 4

In [62]:
e = torch.rand(2,3,28,28)
e.shape #[batch, channel, height, width]

torch.Size([2, 3, 28, 28])

## others

In [63]:
e.shape

torch.Size([2, 3, 28, 28])

In [65]:
e.numel()
# number of elements

4704

In [68]:
e.dim()

4

## 创建tensor

In [69]:
f = np.array([ 2,3,4,5,6,7.7])
torch.from_numpy(f)

tensor([2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.7000], dtype=torch.float64)

In [70]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])