# 基本数据类型

In [1]:
import torch

# 2行3列
a = torch.randn(2, 3)
a

tensor([[ 0.2112,  0.3893,  0.1699],
        [ 0.7008, -0.9513, -0.1250]])

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a, torch.FloatTensor)

True

In [6]:
isinstance(a, torch.cuda.FloatTensor)

False

In [7]:
isinstance(a.cuda(), torch.cuda.FloatTensor)

True

## 标量 dim0 一般用来计算loss

In [8]:
torch.tensor(1.)

tensor(1.)

In [9]:
torch.tensor(1.3)

tensor(1.3000)

## dim 1 一般用来表示bias 或linear input （flatten）

In [11]:
torch.tensor([1.1])

tensor([1.1000])

In [2]:
torch.cuda.FloatTensor([1,2,3])

tensor([1., 2., 3.], device='cuda:0')

In [23]:
# 随机的是
torch.FloatTensor(3)

tensor([9.2196e-41, 6.1989e-06, 0.0000e+00])

In [24]:
import numpy as np 

n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [25]:
torch.from_numpy(n)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

## 判断dim

In [27]:
b = torch.ones(3)
b

tensor([1., 1., 1.])

In [30]:
b.shape

torch.Size([3])

In [31]:
b.size()

torch.Size([3])

## dim2  linear batch input

In [45]:
c = torch.randn(2,3)
c

tensor([[ 1.1936, -1.6424,  1.5530],
        [-0.3289,  1.3141, -0.7251]])

In [46]:
c.size()

torch.Size([2, 3])

In [47]:
c.size(0)

2

In [48]:
c.size(1)

3

In [50]:
list(c.shape)

[2, 3]

## dim3

In [52]:
torch.randn(1,2,3)

tensor([[[ 0.2386,  1.1075,  0.0956],
         [-0.7472, -0.2011, -0.6228]]])

## dim 4

In [62]:
e = torch.rand(2,3,28,28)
e.shape #[batch, channel, height, width]

torch.Size([2, 3, 28, 28])

## others

In [63]:
e.shape

torch.Size([2, 3, 28, 28])

In [65]:
e.numel()
# number of elements

4704

In [68]:
e.dim()

4

## 创建tensor

In [69]:
f = np.array([ 2,3,4,5,6,7.7])
torch.from_numpy(f)

tensor([2.0000, 3.0000, 4.0000, 5.0000, 6.0000, 7.7000], dtype=torch.float64)

In [70]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [2]:
torch.FloatTensor([2,3.2])

tensor([2.0000, 3.2000])

In [3]:
torch.FloatTensor(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

## uninitialized

In [5]:
torch.empty([2,3])

tensor([[7.2868e-44, 8.1275e-44, 6.7262e-44],
        [7.8473e-44, 8.1275e-44, 6.8664e-44]])

In [6]:
torch.FloatTensor(2,3)

tensor([[0.0000e+00, 0.0000e+00, 6.7377e-10],
        [4.2468e-08, 6.7410e+22, 5.4371e+22]])

In [7]:
torch.IntTensor(2,3)

tensor([[ 943285090,  912602465,  878981683],
        [ 859386934,  942815074, 1714906420]], dtype=torch.int32)

## random

In [9]:
torch.rand_like(a)

tensor([[0.5579, 0.1193, 0.3796],
        [0.2175, 0.9457, 0.9643]])

In [11]:
torch.randint(1, 10, [3,4])

tensor([[5, 7, 9, 8],
        [1, 3, 1, 3],
        [2, 4, 4, 8]])

In [12]:
# 正态分布
torch.randn(3,3)

tensor([[-0.9320, -1.1690, -0.9073],
        [-1.0097,  2.0474, -1.0402],
        [-2.7951,  1.2550, -0.7483]])

In [16]:
# 注意使用方法
torch.normal(mean=torch.full([10], 0, dtype=torch.float32), std=torch.arange(1, 0, -0.1, dtype=torch.float32))

tensor([-0.7152,  0.6989,  0.4855, -0.2965,  0.3001, -0.1431, -0.7074,  0.1654,
        -0.0979,  0.1009])

## full

In [17]:
torch.full([2,3,3], 1)

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

In [20]:
# dim 0
torch.full([], 1)

tensor(1)

# arrage

In [22]:
torch.arange(0, 10, 0.2)

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000, 5.0000, 5.2000,
        5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000, 6.8000, 7.0000,
        7.2000, 7.4000, 7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000,
        9.0000, 9.2000, 9.4000, 9.6000, 9.8000])

# linspace

In [24]:
torch.linspace(0, 10, 3)

tensor([ 0.,  5., 10.])

In [25]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

# ones/zeros/eye

In [26]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [28]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# randperm

In [29]:
torch.randperm(10)

tensor([0, 4, 2, 9, 7, 6, 1, 5, 8, 3])

# Indexing

In [3]:
tensor = torch.randn(4,3,28,28)

In [7]:
tensor.shape

torch.Size([4, 3, 28, 28])

In [16]:
tensor[0].shape # dim 0 first

torch.Size([3, 28, 28])

In [17]:
tensor[0,0].shape

torch.Size([28, 28])

In [18]:
tensor[0,0,2,4]

tensor(0.5014)

In [41]:
tensor.index_select(0, torch.tensor([2,3])).shape

torch.Size([2, 3, 28, 28])

In [43]:
tensor.index_select(2, torch.arange(10)).shape

torch.Size([4, 3, 10, 28])

# 切片 与numpy类似

In [20]:
tensor[0:2].shape

torch.Size([2, 3, 28, 28])

In [22]:
tensor[0:2, 0:2, 1:2, 1:3].shape

torch.Size([2, 2, 1, 2])

In [24]:
tensor[:-1,1,1,1]

tensor([ 0.0078, -0.3559,  0.5867])

In [33]:
tensor[:,:,0:10:2].shape

torch.Size([4, 3, 5, 28])

In [45]:
tensor[...].shape # ... 根据实际的shape来推测

torch.Size([4, 3, 28, 28])

In [47]:
tensor[0,...,...,...].shape

torch.Size([3, 28, 28])

In [50]:
tensor[:,...].shape

torch.Size([4, 3, 28, 28])

In [52]:
tensor[...,2].shape

torch.Size([4, 3, 28])

# mask

In [55]:
mask = tensor.ge(0.5)
mask[0,0,0]

tensor([False, False,  True,  True, False, False, False, False, False, False,
        False,  True, False,  True, False, False,  True, False, False,  True,
         True, False,  True, False,  True, False, False, False])

In [56]:
torch.masked_select(tensor, mask) #会变成一列

tensor([0.5408, 0.6012, 1.2412,  ..., 0.6057, 0.7984, 1.4489])

# take

In [58]:
torch.take(tensor, torch.tensor([1,2,4]))

tensor([-0.4735,  0.5408, -0.6458])

In [59]:
tensor.take(torch.tensor([1,2,4]))

tensor([-0.4735,  0.5408, -0.6458])